name: deploy-container
# watch for push event  on master branch
# only run the changes when on container folder
# defaults will set the execution environment to working directory
# run on ubuntu operatin system
# prgramaatic access of AWS cli
on:
  push:     
    branches:
      - master
    paths:
      - 'packages/container/**'

defaults:
  run:
     working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses:actions/checkout@v2
    - run: npm install
    - run: npm run build

    - uses: shinyinc/action-aws-cli@v1.2
    - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/container/latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
